# Generated by Django 4.1.3 on 2022-11-12 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_location_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='places', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='video'),
        ),
    ]
