version: '3.8'

services:
  database:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  frontend:
    build: ./frontend
    container_name: frontend
    command: npm start 0.0.0.0:3000
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    container_name: backend
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - database
    